---

is-debug: true

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 60s
  write_timeout: 60s
  max_header_bytes: 1048576

postgres:
  host: "127.0.0.1"
  port: "5432"
  database: database
  user: postgres
  password: postgres
